import 'package:get/get_navigation/src/routes/get_route.dart';

import '../bind/about_binding.dart';
import '../bind/add_experience_binding.dart';
import '../bind/aditional_binding.dart';
import '../bind/all_category_binding.dart';
import '../bind/all_doctors_binding.dart';
import '../bind/all_review_binding.dart';
import '../bind/appointment_binding.dart';
import '../bind/appointment_details_binding.dart';
import '../bind/bank_details_binding.dart';
import '../bind/book_info_binding.dart';
import '../bind/category_details_binding.dart';
import '../bind/change_password_binding.dart';
import '../bind/chat_binding.dart';
import '../bind/create_schedule_binding.dart';
import '../bind/doctor_details_binding.dart';
import '../bind/doctor_home_binding.dart';
import '../bind/doctor_register_binding.dart';
import '../bind/experience_binding.dart';
import '../bind/find_binding.dart';
import '../bind/forgot_password_binding.dart';
import '../bind/home_binding.dart';
import '../bind/inbox_binding.dart';
import '../bind/liked_tips_binding.dart';
import '../bind/login_binding.dart';
import '../bind/navigation_binding.dart';
import '../bind/notification_binding.dart';
import '../bind/offline_binding.dart';
import '../bind/onboard_binding.dart';
import '../bind/otp_binding.dart';
import '../bind/payment_binding.dart';
import '../bind/policy_binding.dart';
import '../bind/profile_binding.dart';
import '../bind/register_binding.dart';
import '../bind/request_view_binding.dart';
import '../bind/reset_password_binding.dart';
import '../bind/schedule_binding.dart';
import '../bind/service_binding.dart';
import '../bind/setting_binding.dart';
import '../bind/splash_binding.dart';
import '../bind/support_binding.dart';
import '../bind/terms_binding.dart';
import '../bind/tips_binding.dart';
import '../bind/update_profile_binding.dart';
import '../bind/upload_doc_binding.dart';
import '../bind/verification_binding.dart';
import '../bind/video_call_binding.dart';
import '../bind/welcome_binding.dart';
import '../views/about/screen/about_screen.dart';
import '../views/add_experience/screen/add_experience_screen.dart';
import '../views/aditional/screen/aditional_screen.dart';
import '../views/all_category/screen/all_category_screen.dart';
import '../views/all_doctors/screen/all_doctors_screen.dart';
import '../views/all_review/screen/all_review_screen.dart';
import '../views/appointment/screen/appointment_screen.dart';
import '../views/appointment_details/screen/appointment_details_screen.dart';
import '../views/auth/change_password/screen/change_password_screen.dart';
import '../views/auth/doctor_register/screen/doctor_register_screen.dart';
import '../views/auth/forgot_password/screen/forgot_password_screen.dart';
import '../views/auth/login/screen/login_screen.dart';
import '../views/auth/otp/screen/otp_screen.dart';
import '../views/auth/register/screen/register_screen.dart';
import '../views/auth/reset_password/screen/reset_password_screen.dart';
import '../views/auth/verification/screen/verification_screen.dart';
import '../views/bank_details/screen/bank_details_screen.dart';
import '../views/book_info/screen/book_info_screen.dart';
import '../views/category_details/screen/category_details_screen.dart';
import '../views/chat/screen/chat_screen.dart';
import '../views/create_schedule/screen/create_schedule_screen.dart';
import '../views/doctor_details/screen/doctor_details_screen.dart';
import '../views/doctor_home/screen/doctor_home_screen.dart';
import '../views/experience/screen/experience_screen.dart';
import '../views/find/screen/find_screen.dart';
import '../views/home/screen/home_screen.dart';
import '../views/inbox/screen/inbox_screen.dart';
import '../views/liked_tips/screen/liked_tips_screen.dart';
import '../views/navigation/screen/navigation_screen.dart';
import '../views/notification/screen/notification_screen.dart';
import '../views/offline/screen/offline_screen.dart';
import '../views/onboard/screen/onboard_screen.dart';
import '../views/payment/screen/payment_screen.dart';
import '../views/policy/screen/policy_screen.dart';
import '../views/profile/screen/profile_screen.dart';
import '../views/request_view/screen/request_view_screen.dart';
import '../views/schedule/screen/schedule_screen.dart';
import '../views/service/screen/service_screen.dart';
import '../views/setting/screen/setting_screen.dart';
import '../views/splash/screen/splash_screen.dart';
import '../views/support/screen/support_screen.dart';
import '../views/terms/screen/terms_screen.dart';
import '../views/tips/screen/tips_screen.dart';
import '../views/update_profile/screen/update_profile_screen.dart';
import '../views/upload_doc/screen/upload_doc_screen.dart';
import '../views/video_call/screen/video_call_screen.dart';
import '../views/welcome/screen/welcome_screen.dart';

part 'pages.dart';

class Routes {
  static var list = RoutePageList.list;
static const addExperienceScreen = '/add_experienceScreen';
static const serviceScreen = '/serviceScreen';
static const experienceScreen = '/experienceScreen';
static const aboutScreen = '/aboutScreen';
static const createScheduleScreen = '/create_scheduleScreen';
static const scheduleScreen = '/scheduleScreen';
static const chatScreen = '/chatScreen';
static const request_viewScreen = '/request_viewScreen';
static const doctor_homeScreen = '/doctor_homeScreen';
  static const aditionalScreen = '/aditionalScreen';
  static const doctorRegisterScreen = '/doctor_registerScreen';
  static const confirmationScreen = '/confirmationScreen';
  static const updateProfileScreen = '/update_profileScreen';
  static const bankDetailsScreen = '/bank_detailsScreen';
  static const changePasswordScreen = '/change_passwordScreen';
  static const policyScreen = '/policyScreen';
  static const termsScreen = '/termsScreen';
  static const supportScreen = '/supportScreen';
  static const settingScreen = '/settingScreen';
  static const videoCallScreen = '/video_callScreen';
  static const inboxScreen = '/inboxScreen';
  static const appointmentDetailsScreen = '/appointment_detailsScreen';
  static const categoryDetailsScreen = '/category_detailsScreen';
  static const likedTipsScreen = '/liked_tipsScreen';
  static const paymentScreen = '/paymentScreen';
  static const bookInfoScreen = '/book_infoScreen';
  static const allReviewScreen = '/all_reviewScreen';
  static const doctorDetailsScreen = '/doctor_detailsScreen';
  static const allDoctorsScreen = '/all_doctorsScreen';
  static const allCategoryScreen = '/all_categoryScreen';
  static const notificationScreen = '/notificationScreen';
  static const tipsScreen = '/tipsScreen';
  static const profileScreen = '/profileScreen';
  static const appointmentScreen = '/appointmentScreen';
  static const findScreen = '/findScreen';
  static const homeScreen = '/homeScreen';
  static const welcomeScreen = '/welcomeScreen';
  static const verificationScreen = '/verificationScreen';
  static const navigationScreen = '/navigationScreen';
  static const onboardScreen = '/onboardScreen';
  static const uploadDocScreen = '/upload_docScreen';
  static const resetPasswordScreen = '/reset_passwordScreen';
  static const otpScreen = '/otpScreen';
  static const forgotPasswordScreen = '/forgot_passwordScreen';
  static const registerScreen = '/registerScreen';
  static const loginScreen = '/loginScreen';
  static const offlineScreen = '/offlineScreen';
  static const splashScreen = '/splashScreen';
}
